#!/system/bin/sh
# Volume Steps+ for Magisk 17+
# Original source by: veez21 @xda-developers 2017
# Remake and Upgrade by: WilomanCZ 2018


# Default Variables
div="=================================";
MODDIR="/sbin/.magisk/img/VolumeStepsPlus";
MODDIR2=$MODDIR/system/xbin;
prop=$MODDIR/system.prop;

# Functions
get_file_prop() {
_prop=$2
_prop=$(grep "$1=" $_prop)
val=${_prop#*=}
echo $val
unset _prop
}
set_file_prop() {
_prop=$3
sed -i "s/${1}=.*/${1}=${2}/g" $_prop
unset _prop
}

# Extra Variables
VER=$(get_file_prop version $MODDIR/module.prop);
REL=$(get_file_prop versionCode $MODDIR/module.prop);
AUT=$(get_file_prop author $MODDIR/module.prop);
NAM=$(get_file_prop name $MODDIR/module.prop);

clear;

echo $div;
echo "${NAM} menu   -   Version: ${VER}.${REL}";
echo "Author: $AUT";
echo $div;
echo "";
echo $div;

echo "Choose function to edit: ";
echo "" ;

echo "a (A/1)    - Media-Volume Steps Count CONFIG";
echo "b (B/2)    - Call-Volume Steps Count CONFIG ";
echo "c (C/3)    - Safe Media ByPass CONFIG";
echo "q (Q/4)    - For EXIT";

echo $div;

echo -n "Write selection  (a,b,c or q) or (1,2,3 or 4):";
read selection

if [ "$selection" == "" ] || [ "$selection" == "1" ] || [ "$selection" == "a" ] || [ "$selection" == "A" ]; then
clear;
  SCRN="Media-Volume Steps";
  scfile=$MODDIR2/mediasteps;
  echo "You choosed:  ${SCRN}";
  sleep 2;
  sh $scfile;

elif [ "$selection" == "2" ] || [ "$selection" == "b" ] || [ "$selection" == "B" ]; then
clear;
  SCRN="Call-Volume Steps":
  scfile=$MODDIR2/callsteps;
  echo "You choosed:  ${SCRN}";
  sleep 2;
  sh $scfile;

elif [ "$selection" == "3" ] || [ "$selection" == "c" ] || [ "$selection" == "C" ]; then
clear;
  SCRN="Safe Media ByPass";
  scfile=$MODDIR2/soundbypass;
  echo "You choosed:  ${SCRN}";
  sleep 2;
  sh $scfile;

elif [ "$selection" == "4" ] || [ "$selection" == "q" ] || [ "$selection" == "Q" ]; then
clear;
  SCRN="Exit";
  echo "You choosed:  ${SCRN}";
  sleep 4;
  exit;

else
clear;
scfile=$MODDIR2/VoSte;
       echo "You Choosed: ${selection}";
       echo "This is not correct selection.";
       echo "You can choose only: a(1),b(2),c(3) or q.";
       sleep 3;
       clear;
       sh $scfile;
       exit;
fi
