#!/system/bin/sh
# Call Volume Steps+ for Magisk 17+
# Original source by: veez21 @xda-developers 
# Remake and Upgrade by: WilomanCZ


# Default Variables
div="=================================";
MODDIR="/sbin/.magisk/img/VolumeStepsPlus";
MODDIR2=$MODDIR/system/xbin;
scfile=$MODDIR2/callsteps;
prop=$MODDIR/system.prop;

# Functions
get_file_prop() {
_prop=$2
_prop=$(grep "$1=" $_prop)
val=${_prop#*=}
echo $val
unset _prop
}

set_file_prop() {
_prop=$3
sed -i "s/${1}=.*/${1}=${2}/g" $_prop
unset _prop
}

# Extra Variables
VER=$(get_file_prop version $MODDIR/module.prop);
REL=$(get_file_prop versionCode $MODDIR/module.prop);
AUT=$(get_file_prop author $MODDIR/module.prop);
NAM=$(get_file_prop name $MODDIR/module.prop);
SCRN="Call-Volume Steps";

# Main
clear;

current=$(getprop ro.config.vc_call_vol_steps);
applied=$(get_file_prop ro.config.vc_call_vol_steps $prop);

echo $div;
echo "Increase $SCRN - ${NAM}";
echo $div;
echo "";
echo "Version: ${VER}.${REL}";
echo "Author: $AUT";
echo "";
echo "Set own value of $SCRN Count";
echo $div;
echo "";
echo $div;
echo "Current: $current";

if [ "$current" -ne "$applied" ]; then
	echo "To be applied: $applied" ;
	echo "NOTE: REBOOT TO APPLY CHANGES";
fi 

echo $div;
echo "";
echo -n "Write number of steps count (q for exit):";
read volume

if [ "$volume" == "$applied" ]; then
	echo "Already entered";
	exit;
elif [ "$volume" == "q" ] || [ "$volume" == "Q" ]; then
clear;
	echo "Exit";
	sleep 1;
	exit;
	
elif [ "$volume" == "" ] || [ -n "$(echo $volume | tr -d '0-9')" ]; then
	echo "Number only! Try it again.";
	sleep 2;
	sh $scfile;
	exit;
else
	echo "Changing to: ${volume}";
	sleep 1;
set_file_prop ro.config.vc_call_vol_steps ${volume} $prop;
	echo "Reboot device to apply changes.";
	echo -n "Do you want reboot device now? (y/n) or empty is NO :" ;
	read reb
	   if [ "$reb" == "y" ] || [ "$reb" == "Y" ]; then
	reboot;
	  elif [ "$reb" == "" ] || [ "$reb" == "n" ] || [ "$reb" == "N" ]; then
	exit ;
fi 
    exit;
fi
